title: Marlarky
description: Generate syntactically plausible English nonsense, steered by lexicons.
remote_theme: just-the-docs/just-the-docs

url: ""
baseurl: "/marlarky"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

aux_links:
  "GitHub":
    - "https://github.com/wonder/marlarky"
aux_links_new_tab: true

footer_content: "Marlarky &copy; 2026. Distributed under the MIT License."

color_scheme: default

search_enabled: true
search.button: true

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

nav_sort: case_insensitive

enable_copy_code_button: true

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red

exclude:
  - Gemfile
  - Gemfile.lock
